import * as fs from 'fs';
import * as path from 'path';
import { getGitRevision } from './git-helper';

const BASE_PATH = path.join(__dirname, '../../src/environments');

console.log(`Updating ${BASE_PATH}/version.ts with new revision`);
saveRevisionVersion();

function saveRevisionVersion() {
  try {
    const revision = getGitRevision();
    console.log('Revision:', revision);
    fs.writeFileSync(`${BASE_PATH}/version.prod.ts`, getFileContents(revision), { encoding: 'utf8' });
    process.exit(0);
  } catch (ex) {
    process.exit(1);
  }
}

function getFileContents(revision: string): string {
  let content = `// this file is automatically generated by /tasks/rollbar/set-version.ts script\n`;
  content += `export const versions = { revision: '${revision}', buildDate: '${new Date().toJSON()}' };\n`;
  content += `export const ROLLBAR_ACCESS_TOKEN = '${process.env.ROLLBAR_ACCESS_TOKEN || '1728a5ba1ff64b0cbc2a786b35f1c7d3'}';\n`;
  return content;
}
